### ISSUE TITLE
Catch file deleted from computer error

### ISSUE THREAD

**Issue by AhmedbGayess** [hgouveia/node-downloader-helper#36]
When I delete a file while it's still downloading, how do I catch the error so I can handle it? I don't get anything in on('error') and I have no clue where else it could come from

**Comment by hgouveia** [comment]
@AhmedbGayess sadly there is no way for this since the lib will recreate the file and append the latest byte chunk it had if am not wrong,  i am surprised this can be done since the file should be lock by the filestream

if you are not using any pipe for compress or something, you could check the filesize in the progress event and compare with the downloaded size, if doesn't match, probably was removed before

**Comment by AhmedbGayess** [comment]
Thanks for responding so quick! I guess I'll use something like node-watch to monitor any changes

**Comment by hgouveia** [comment]
> Thanks for responding so quick! I guess I'll use something like node-watch to monitor any changes

yeap that could be a good solution!
Thanks
