### ISSUE TITLE
Implement file integrity check 

### ISSUE THREAD

**Issue by leohubert** [hgouveia/node-downloader-helper#37]
Hi ! 
It would be great to check the file integrity after download, if checksum was not correct `retry`.

I implemented this feature on my project and when i have a time i create a PR to add this feature here ?
https://github.com/emodyz/NodeDownloader

Is it ok for you @hgouveia ?

**Comment by hgouveia** [comment]
Hello, @leohubert I think this is a very good utility but not sure if the downloader should cover it since this is a separate task that happens after the file is downloaded and not a downloader responsibility. 

I don't want to add more complexity if not necessary, I actually do the same in a project where I use this lib, but I do this process separately, also because the integrity check could be a different algorithm or  process

**Comment by leohubert** [comment]
No problems :) 

So you can close this issue :D
